# Generated by Django 5.1.1 on 2026-07-13 09:31

import users.validators
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    users.validators.validate_reserved_username,
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                ],
            ),
        ),
    ]
